### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by impredicative** [vqdang/xy_net#1]
Your paper says:

> Model code available at: https://github.com/vqdang/xy_net

I look forward to it. Thanks.

**Comment by simongraham** [comment]
Thank you for your comment. The paper will have full code on the repo within a week. We have delayed the upload of the code to ensure things are written clearly for others to use. We will inform you when the code is ready.

Thank you for your patience

**Comment by simongraham** [comment]
The code is now available online. We will also continue to clean up the code over the coming weeks. I will now close this issue. Please get in touch with any queries.
